### ISSUE TITLE
Release source code

### ISSUE THREAD

**Issue by eeowaa** [asleepysamurai/socketwrench#3]
This looks like a really cool app, but without the source code, I can't trust it. Something like this would be perfect for performing MitM attacks on unsuspecting developers. Would you please consider open-sourcing this application? Or maybe it is already released and I just can't find it.

**Comment by asleepysamurai** [comment]
I understand this concern, but as of yet I have not decided on whether I
would want to monetize this application. I'm waiting to see how the
adoption is, too figure out if it's worth monetizing, so until I make that
decision and decide on how exactly it's going to be monetized, I'll not be
able to open source the application.


If the usage and adoption stats do not support monetization, then I'll open
source the app. As of now, the only data that is collected is the amount of
time that the application is open, and what view is open (server page,
about page etc). Unfortunately I can't really prove that without showing
the code, so you'll have to take my word for it now.


If I decide to open source the app, I will update this issue and upload the
code to this repo.

**Comment by eeowaa** [comment]
OK, that's understandable. But you may lose market share with what I think is a very promising application by developers like me (and there's a lot of us) who will shy away from it. In any case, good luck with your business endeavors.

**Comment by jonjaques** [comment]
1. open dmg
2. right click socketwrench > show package contents
3. find app.asar
4. npx asar extract app.asar destfolder

Kudos for not lying :)

**Comment by jonjaques** [comment]
BTW, I think Insomnia has a good model w/ hosted collaboration platform. There's no use in trying to close source JS that gets delivered to the enduser.
